# Generated by Django 6.0 on 2026-09-03 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ThematicArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(blank=True, max_length=100)),
                ('summary', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PCMCAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('ongoing', 'Ongoing'), ('done', 'Done')], default='planned', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('thematic_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pcmc_actions', to='content.thematicarea')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='KeyStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=150)),
                ('value', models.CharField(max_length=150)),
                ('thematic_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_stats', to='content.thematicarea')),
            ],
        ),
        migrations.CreateModel(
            name='CitizenAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('thematic_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citizen_actions', to='content.thematicarea')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('thematic_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='content.thematicarea')),
            ],
        ),
        migrations.CreateModel(
            name='VulnerableGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('thematic_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vulnerable_groups', to='content.thematicarea')),
            ],
        ),
    ]
